Removed external references in requests tests.
hypertrace/pythonagent pull request #180
Opened 2021-05-03 03:00 UTC by rcbjBlueMars

## Description
Remove calls to external endpoints from test suite.

### Testing
* Test suite runs successfully.
* 
### Documentation
* These changes do not modify the documentation.

2021-05-03 08:30 UTC, jcchavezs commented on tests/aiohttp/flask_app/app1.py
> +def testAPI2():
Please use descriptive names for tests e.g. what this test is trying to assert or test. A good example can be found here:

https://github.com/hypertrace/goagent/blob/main/instrumentation/opentelemetry/net/hyperhttp/handler_test.go#L22

2021-05-03 08:30 UTC, jcchavezs commented on tests/aiohttp/flask_app/app1.py
> +def testAPI1():
What is this exactly doing?

2021-05-03 08:31 UTC, jcchavezs commented on tests/aiohttp/flask_app/app1.py
> +      logger.error('Failed to initialize postgresql instrumentation wrapper: exception=%s, stacktrace=%s',
Is this log right?

2021-05-03 08:34 UTC, jcchavezs commented on tests/aiohttp/flask_app/app1.py
> +    if request.base_url != '/route1':
Is this right? I am not exactly sure what these tests for but if we are receiving a request to a non expected endpoint we should fail I think?

2021-05-03 08:35 UTC, jcchavezs commented on tests/aiohttp/test_aiohttp_1.py
> +    async with session.post('http://localhost:8000/route1', data='{ "a":"b", "c": "d" }', headers={ 'tester1': 'tester1', 'tester2':'tester2' }) as response:
I'd really prefer to use meaningful values for the tests, this way it is easier to catch dummy issues.

2021-05-03 08:37 UTC, jcchavezs commented on tests/aiohttp/tox.ini
> +    sleep 10
I'd really avoid this non deterministic sleeps. Can't we use health endpoints?

2021-05-03 08:38 UTC, jcchavezs commented on tests/aiohttp/tox.ini
> +#    pytest -rPx test_aiohttp_3.py
If not use, shall we remove it?

2021-05-03 08:41 UTC, jcchavezs commented on tests/requests/flask_app/app2.py
> +    # Flask extended span object attributes should look like:
This kind of documentation is somehow meaningless in tests. If this is important we should have assertions instead.

2021-05-03 08:41 UTC, jcchavezs commented on tests/requests/flask_app/app2.py
> +  jaegerExporter = JaegerExporter(
I am curious about this. Why exactly do we export on jaeger which uses thrift I think? Can't we export over JSON using e.g. zipkin or OTLP?

2021-05-03 08:42 UTC, jcchavezs requested changes
Thanks @rcbjBlueMars I added a bunch of comments.

2021-05-04 03:11 UTC, rcbjBlueMars commented
The aiohttp tests no longer make exteral calls.

The original intent of this PR has been addressed. I will now address the feedback @jcchavezs provided.

2021-05-13 10:51 UTC, jcchavezs commented
Closed as agreed with @rcbjBlueMars

2021-05-13 10:51 UTC, closed without merging